// Do the design documents still describe the platform that ships?
//
// The characteristic failure of a design doc is a number that was true when it was
// typed. Two of the counts in facts.json were wrong on their first run — `it(` missed
// all 87 Playwright tests, and a field named `emptyAxes` counted every axes figure — and
// both would have been quoted in a document as evidence.
//
// So the docs are generated from facts.json (tools/gen-docs.cjs) and this file closes
// the loop twice: facts.json must agree with the source it claims to measure, and the
// generated docs must agree with facts.json.
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { CHECKS } from "@/lib/checks";
import { CHECKPOINTS, CONCEPTS, ORDERED_DOMAINS } from "@/lib/curriculum";
import { LESSONS } from "@/lib/lessons";
import { BUILDS } from "@/lib/build";
import { ROUTES, STAGES } from "@/lib/routes";
import { CLUSTERS, ARCHITECTURES, ENTRIES } from "@/lib/codex";

const DOCS = "docs/transformation";
const facts = JSON.parse(readFileSync(`${DOCS}/facts.json`, "utf8"));
const CONCEPT_LESSONS = LESSONS.flatMap((l) => l.concepts);
/** A newline as a binding — see the same note in tools/gen-docs.cjs. */
const NL = String.fromCharCode(10);

// Regenerated by tools/gen-docs42.cjs — the section 42 set.
const GENERATED_42 = [
  "engagement-model.md", "retention-engine.md", "evaluation-system.md", "interview-mode.md",
  "diagram-standards.md", "code-example-policy.md", "aws-architecture-standard.md",
  "review-queue-model.md", "question-bank-audit.md", "saved-content-model.md",
  "interview-question-audit.md", "visual-value-report.md",
  "concept-work-package-template.md", "module-work-package-template.md",
  "architecture-work-package-template.md",
];

// Regenerated by tools/gen-docs.cjs; each must agree with facts.json.
const GENERATED = [
  // STATUS.md is the section 28 dashboard. It used to be hand-written, and said "the
  // route model is designed but not built" for four commits after it shipped, with
  // metrics from three commits before that. A dashboard is the document most likely to
  // go stale, so it is generated and asserted like the rest.
  "STATUS.md",
  "target-learning-model.md",
  "validation-report.md",
  "analytics-plan.md",
  "accessibility-audit.md",
  "visual-asset-audit.md",
  "migration-map.md",
  "rollout-plan.md",
];

describe("facts.json agrees with the source it measures", () => {
  it("counts the content the app actually loads", () => {
    // Measured against the TypeScript modules, not by re-reading the JSON the generator
    // read. Re-parsing the same file would only prove JSON.parse is deterministic.
    expect(facts.content.spineConcepts).toBe(CONCEPTS.length);
    expect(facts.content.lessons).toBe(LESSONS.length);
    expect(facts.content.conceptLessons).toBe(CONCEPT_LESSONS.length);
    expect(facts.content.checkpoints).toBe(CHECKPOINTS.length);
    expect(facts.content.checkpointItems).toBe(CHECKPOINTS.reduce((a, c) => a + c.items.length, 0));
    expect(facts.content.checks).toBe(CHECKS.length);
    expect(facts.content.builds).toBe(BUILDS.length);
    expect(facts.content.domains).toBe(ORDERED_DOMAINS.length);
  });

  it("counts each check mechanic correctly", () => {
    const byKind: Record<string, number> = {};
    for (const k of CHECKS) byKind[k.kind] = (byKind[k.kind] ?? 0) + 1;
    expect(facts.content.checksByKind).toEqual(byKind);
  });

  it("measures the route model rather than restating it", () => {
    expect(facts.routing.stageCount).toBe(STAGES.length);
    for (const r of ROUTES) expect(facts.routing.routeIds).toContain(r.id);
  });

  it("the learning-stage coverage is derived from the content", () => {
    expect(facts.learningModel.coverage.predict)
      .toBe(CONCEPT_LESSONS.filter((c) => c.predict).length);
    expect(facts.learningModel.coverage.recall)
      .toBe(CONCEPT_LESSONS.filter((c) => c.flashcards?.length).length);
    expect(facts.learningModel.coverage.worked)
      .toBe(CONCEPT_LESSONS.filter((c) => c.example).length);
    expect(facts.learningModel.coverage.practice)
      .toBe(CONCEPT_LESSONS.filter((c) => CHECKS.some((k) => k.concept === c.slug)).length);
    expect(facts.learningModel.totalConcepts).toBe(CONCEPT_LESSONS.length);
  });

  it("reports Explain as absent, because it is", () => {
    // Explain needs free-text grading, which needs a server. This platform is a static
    // export with no API routes, so the stage is blocked by the deployment model rather
    // than by effort — see target-learning-model.md. If it is ever built, this test
    // SHOULD fail, which is the signal to rewrite that section.
    expect(facts.learningModel.coverage.explain, "Explain now exists — update the docs").toBe(0);
  });

  it("counts a Transfer item only when it is TAGGED as one", () => {
    // This test previously asserted `transfer: 0`, and six transfer items were already
    // shipping. Both were right: the items existed and nothing marked them, so no gate
    // could tell them from an ordinary check. `transferTo` is that mark.
    //
    // The assertion is derived from the content rather than restated, so authoring a
    // seventh item moves it without an edit here.
    const tagged = CHECKS.filter((k) => (k as { transferTo?: string }).transferTo);
    expect(tagged.length, "no check is tagged as a transfer item").toBeGreaterThan(0);
    const concepts = new Set(tagged.map((k) => k.concept));
    expect(facts.learningModel.coverage.transfer).toBe(concepts.size);
  });

  it("every Transfer item names a domain its concept genuinely relates to", () => {
    // The rule merge-checks.cjs enforces, asserted here too because it is the property
    // that keeps the coverage number meaningful. Without it, `transferTo` becomes a
    // free-text label meaning "this feels cross-domain".
    const domainOf = new Map(CONCEPTS.map((c) => [c.concept.slug, c.domainId]));
    const related = new Map<string, Set<string>>();
    for (const c of CONCEPTS) {
      for (const lean of c.concept.leansOn ?? []) {
        const target = domainOf.get(lean);
        if (!target || target === c.domainId) continue;
        if (!related.has(lean)) related.set(lean, new Set());
        related.get(lean)!.add(c.domainId);
      }
    }
    const bad: string[] = [];
    for (const k of CHECKS) {
      const to = (k as { transferTo?: string }).transferTo;
      if (!to) continue;
      if (to === domainOf.get(k.concept)) { bad.push(`${k.id}: transfers to its own domain`); continue; }
      if (!related.get(k.concept)?.has(to)) bad.push(`${k.id}: no leansOn edge to ${to}`);
    }
    expect(bad, "a transfer claim is unfounded").toEqual([]);
  });

  it("reports zero analytics, and would notice instrumentation appearing", () => {
    expect(facts.analytics.trackingCalls).toBe(0);
    expect(facts.analytics.fetchCallsToApi).toBe(0);
  });

  it("separates structural empty strings from missing translations", () => {
    // The naive count is 7 and every one is correct content: three cloze checks whose
    // sentence opens with a blank, and one deliberate `kind: "none"` figure opt-out.
    // Reporting "7 empty strings" would describe a translation gap that does not exist.
    expect(facts.i18n.emptyProse, "a real translation gap has appeared").toBe(0);

    // `emptyStructural === structuralPaths.length` was a tautology: the generator
    // increments the counter and pushes the path in the same statement, so they cannot
    // diverge. And matching the paths against `/(\.segments\.\d+\.|caption)/` reused the
    // generator's own classifier, loosened — bare `caption` instead of `kind: "none"` —
    // so it accepted a superset of what the generator emits.
    //
    // Verified against the CONTENT instead: every path the generator called structural is
    // resolved in the shipped JSON and confirmed to be a positional slot. A caption is
    // only exempt when its diagram is the deliberate `kind: "none"` opt-out.
    const data: Record<string, unknown> = {};
    for (const f of ["lessons.json", "checks.json", "curriculum.json", "codex.json", "builds.json", "resources.json"]) {
      data[f] = JSON.parse(readFileSync(`src/content/data/${f}`, "utf8"));
    }
    // The generator emits `lessons.json.lessons.27.concepts.3.diagram.caption.en`, so the
    // filename's own dot has to be split off FIRST. Splitting the whole path on "." turned
    // `json` into a key and every lookup resolved to undefined — the test then reported
    // "does not resolve in the shipped content" for a path that resolves fine.
    const split = (path: string) => {
      const file = Object.keys(data).find((f) => path.startsWith(`${f}.`));
      return { file, keys: file ? path.slice(file.length + 1).split(".") : [] };
    };
    const at = (path: string) => {
      const { file, keys } = split(path);
      let node: unknown = file ? data[file] : undefined;
      for (const k of keys) {
        if (node === undefined || node === null) return { node: undefined };
        node = (node as Record<string, unknown>)[k];
      }
      return { node };
    };
    /** The object two levels up — for `…diagram.caption.en` that is the diagram itself. */
    const parentOf = (path: string) => {
      const { file, keys } = split(path);
      if (!file) return undefined;
      return at(`${file}.${keys.slice(0, -2).join(".")}`).node as Record<string, unknown> | undefined;
    };

    expect((facts.i18n.structuralPaths as string[]).length, "no structural slots — did the classifier break?")
      .toBeGreaterThan(0);
    for (const path of facts.i18n.structuralPaths as string[]) {
      const { node } = at(path);
      expect(node, `${path} does not resolve in the shipped content`).toBeDefined();
      expect(String(node).trim(), `${path} is not actually empty`).toBe("");

      const isSegment = /\.segments\.\d+\./.test(path);
      const parent = parentOf(path);
      const isNoneDiagram = !isSegment && parent?.kind === "none";
      expect(
        isSegment || isNoneDiagram,
        `${path} is empty but is neither a cloze segment nor a kind:"none" caption — it is a missing translation`,
      ).toBe(true);
    }
  });

  it("has exactly as many Spanish strings as English ones", () => {
    expect(facts.i18n.es).toBe(facts.i18n.en);
  });

  it("counts TESTS, not call sites — the runners are the authority", () => {
    // Two regexes were wrong here in sequence, and this test enforced the second one.
    //
    //   1. `it(` matched zero of the Playwright tests, because Playwright uses `test(`.
    //   2. Matching both was STILL wrong: a test generated inside a `for` loop is one
    //      call site and many tests. Six spec files undercounted, the total read 89
    //      against a real 110 — and the AI-route sweep I wrote myself was one of them.
    //
    // This test recomputed the generator's own regex, so it passed against the defect. A
    // count of source lines cannot be validated by counting source lines again. The
    // generator now shells out to `--list`, and this asserts it did so rather than
    // falling back, because a silent fallback is how an estimate becomes a "measurement".
    const specs = readdirSync("tests/visual").filter((f) => f.endsWith(".spec.ts"));
    expect(facts.validation.e2eSpecFiles).toBe(specs.length);
    expect(facts.validation.e2eTestsFrom, "the e2e count fell back to counting call sites")
      .toBe("playwright --list");
    expect(facts.validation.unitTestsFrom, "the unit count fell back to counting call sites")
      .toBe("vitest list");

    // And the runner-derived figure must EXCEED the call-site count, since a loop
    // generates more tests than lines. Equal would mean no loop-generated test exists,
    // which is false for this suite — the sweep in predict.spec.ts is one.
    const callSites = specs.reduce(
      (a, f) => a + (readFileSync(`tests/visual/${f}`, "utf8").match(/^\s*(?:it|test)\(/gm) || []).length, 0);
    expect(facts.validation.e2eTests, "the runner count should exceed the call-site count")
      .toBeGreaterThan(callSites);
  });

  it("counts the validators the verify script actually runs", () => {
    const pkg = JSON.parse(readFileSync("package.json", "utf8"));
    const steps = (name: string) => pkg.scripts[name].split("&&").map((s: string) => s.trim()).filter(Boolean);
    // A validator and a chain step are not the same thing. `content:check` runs
    // gen-glossary.cjs before check-glossary.cjs so the measured usage counts cannot be
    // stale, and counting that generator as a validator reported 12 gates where 11
    // exist — a number that would have gone into STATUS.md and validation-report.md as
    // evidence. Both are asserted, and the generator is required to be excluded.
    const chain = steps("content:check");
    const generators = chain.filter((s: string) => s.includes("/gen-"));
    expect(facts.validation.contentCheckSteps).toBe(chain.length);
    expect(facts.validation.contentValidators).toBe(chain.length - generators.length);
    expect(generators.length, "a generator in content:check is being counted as a gate")
      .toBeGreaterThan(0);
    expect(facts.validation.selfTests).toBe(steps("gates:selftest").length);
    expect(facts.validation.verifySteps).toBe(steps("verify").length);
  });
});

describe("every countable fact is re-derived, not just carried", () => {
  // The backstop. 64 of 125 leaves were referenced by no assertion at all, and one of them
  // (`visual.axesFigures`) had shipped under a name that misdescribed what it counted.
  const CL = LESSONS.flatMap((l) => l.concepts);

  it("re-derives every content count from the modules the app loads", () => {
    // A table rather than 20 separate its: adding a content fact to the generator without a
    // derivation here shows up in the ratio test below.
    const derived: Record<string, number> = {
      midQuizItems: LESSONS.reduce((a, l) => a + (l.midQuiz?.length ?? 0), 0),
      codexEntries: ENTRIES.length,
      codexClusters: CLUSTERS.length,
      codexArchitectures: ARCHITECTURES.length,
      conceptsWithCode: CL.filter((c) => c.code).length,
      conceptsWithExample: CL.filter((c) => c.example).length,
      conceptsWithPitfalls: CL.filter((c) => c.pitfalls?.length).length,
      conceptsWithFlashcards: CL.filter((c) => c.flashcards?.length).length,
      conceptsWithPredict: CL.filter((c) => c.predict).length,
      leansOnEdges: CONCEPTS.reduce((a, c) => a + (c.concept.leansOn?.length ?? 0), 0),
      prerequisiteEdges: CONCEPTS.reduce((a, c) => a + (c.concept.prerequisites?.length ?? 0), 0),
    };
    for (const [k, v] of Object.entries(derived)) {
      expect(facts.content[k], `content.${k} disagrees with the content`).toBe(v);
    }
  });

  it("re-derives the figure counts, including the field that once misnamed itself", () => {
    // `axesFigures` was called `emptyAxes` and counted EVERY axes figure. The name asserted
    // something the expression did not compute, and nothing checked it.
    const figures: { kind: string; caption?: { en?: string } }[] = [];
    for (const c of CL) {
      if (c.diagram) figures.push(c.diagram as never);
      if (c.architecture) figures.push(c.architecture as never);
    }
    for (const e of ENTRIES) if (e.diagram) figures.push(e.diagram as never);
    for (const a of ARCHITECTURES) if (a.diagram) figures.push(a.diagram as never);

    expect(facts.visual.figures, "the figure total disagrees with the content").toBe(figures.length);
    expect(facts.visual.axesFigures, "axesFigures should count axes figures, nothing else")
      .toBe(figures.filter((f) => f.kind === "axes").length);
    expect(facts.visual.withoutCaption, "withoutCaption disagrees with the content")
      .toBe(figures.filter((f) => !f.caption?.en?.trim()).length);
    expect(facts.visual.conceptsUsingWidget).toBe(CL.filter((c) => c.visual).length);

    const byKind: Record<string, number> = {};
    for (const f of figures) byKind[f.kind] = (byKind[f.kind] ?? 0) + 1;
    expect(facts.visual.byKind, "the per-kind figure counts disagree").toEqual(byKind);
  });

  it("re-derives the asset and file counts from disk", () => {
    const walk = (dir: string, acc: string[] = []): string[] => {
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        if (e.isDirectory()) walk(`${dir}/${e.name}`, acc);
        else acc.push(`${dir}/${e.name}`);
      }
      return acc;
    };
    const assets = walk("public");
    expect(facts.visual.publicAssets).toBe(assets.length);
    expect(facts.visual.publicBytes).toBe(assets.reduce((a, f) => a + statSync(f).size, 0));
    expect(facts.visual.interactiveWidgets)
      .toBe(readdirSync("src/components/viz").filter((f) => f.endsWith(".tsx")).length);
    expect(facts.a11y.cssFiles)
      .toBe(readdirSync("src/app/styles").filter((f) => f.endsWith(".css")).length);
    expect(facts.validation.baselineFiles)
      .toBe(readdirSync("tools").filter((f) => /baseline/.test(f)).length);
    expect(facts.validation.unitTestFiles)
      .toBe(walk("tests").filter((f) => /\.test\.ts$/.test(f)).length);
  });

  it("re-derives the character totals, so the bilingual claim is measured", () => {
    // `enChars`/`esChars` back the "equivalent editorial versions" claim in
    // terminology-policy.md and were referenced nowhere.
    let en = 0, es = 0;
    const walk = (o: unknown): void => {
      if (!o || typeof o !== "object") return;
      for (const [k, v] of Object.entries(o as Record<string, unknown>)) {
        if (typeof v === "string") { if (k === "en") en += v.length; else if (k === "es") es += v.length; }
        else walk(v);
      }
    };
    for (const f of ["curriculum.json", "lessons.json", "codex.json", "checks.json", "builds.json", "resources.json"]) {
      walk(JSON.parse(readFileSync(`src/content/data/${f}`, "utf8")));
    }
    expect(facts.i18n.enChars).toBe(en);
    expect(facts.i18n.esChars).toBe(es);
    // Spanish runs longer than English; a ratio below 1 would mean the es side is a stub.
    expect(es / en, "the Spanish edition is materially shorter than the English").toBeGreaterThan(0.95);
  });

  it("re-derives the spaced-review and streak facts from the engine", () => {
    // `systems.spacedReview` and `systems.streak` back every claim in
    // retention-engine.md and were referenced by no assertion at all.
    const review = readFileSync("src/lib/review.ts", "utf8");
    const daily = readFileSync("src/lib/daily.ts", "utf8");

    const intervals = review.match(/export const INTERVALS = \[([^\]]+)\]/)![1]
      .split(",").map((x) => x.trim()).filter(Boolean);
    expect(facts.systems.spacedReview.intervals, "the interval ladder disagrees with review.ts")
      .toEqual(intervals);
    expect(facts.systems.spacedReview.grades.length, "the grade set disagrees with review.ts")
      .toBe(review.match(/export type Grade =([^;]+);/)![1].split("|").length);
    expect(facts.systems.spacedReview.easeRange)
      .toEqual([review.match(/EASE_MIN = ([\d.]+)/)![1], review.match(/EASE_MAX = ([\d.]+)/)![1]]);
    // Purity is load-bearing: Date.now()/Math.random() at runtime break hydration parity
    // on a static export, so this is a real property and not a comment.
    expect(facts.systems.spacedReview.pure).toBe(true);
    expect(review, "review.ts is no longer pure — it reads the clock").not.toMatch(/Date\.now\(\)/);
    expect(review, "review.ts is no longer pure — it uses randomness").not.toMatch(/Math\.random\(\)/);

    expect(facts.systems.reviewQueue.dailyCap)
      .toBe(Number(daily.match(/REVIEW_CAP = (\d+)/)![1]));
    expect(facts.systems.streak.exists).toBe(/export function markDay/.test(daily));
    // The streak is forgiving on purpose: loss aversion drives short-term engagement and
    // long-term churn, so a missed day must not zero the counter.
    expect(facts.systems.streak.forgiving).toBe(true);
  });

  it("re-derives the glossary facts from the generated files", () => {
    const g = JSON.parse(readFileSync("content/glossary.en.json", "utf8"));
    expect(facts.glossary.terms).toBe(g.terms.length);
    expect(facts.glossary.kept).toBe(g.terms.filter((t: { translate: boolean }) => !t.translate).length);
    expect(facts.glossary.localized).toBe(g.terms.filter((t: { translate: boolean }) => t.translate).length);
    expect(facts.glossary.bans).toBe(g.terms.reduce((a: number, t: { avoid: string[] }) => a + t.avoid.length, 0));
    expect(facts.glossary.withNote).toBe(g.terms.filter((t: { note?: string }) => t.note).length);
    expect(facts.glossary.kept + facts.glossary.localized, "every term is kept or localized")
      .toBe(facts.glossary.terms);
  });

  it("keeps most of facts.json under assertion, so coverage cannot quietly decay", () => {
    // The meta-test. Adding fields to the generator with no assertions makes this fail,
    // which is the signal to assert them rather than to raise the threshold.
    const leaves: string[] = [];
    const walk = (o: Record<string, unknown>, path: string) => {
      for (const [k, v] of Object.entries(o)) {
        const at = path ? `${path}.${k}` : k;
        if (v !== null && typeof v === "object" && !Array.isArray(v)) walk(v as Record<string, unknown>, at);
        else leaves.push(at);
      }
    };
    walk(facts, "");
    const src = readFileSync("tests/facts.test.ts", "utf8");
    // A leaf is covered if IT or any ANCESTOR is named, because
    // `expect(facts.visual.byKind).toEqual(byKind)` covers all five of its children
    // without naming one of them. The first version of this check only looked at the leaf's
    // own key and reported 60 gaps where 3 existed — measuring the wrong thing, which is
    // the error this whole file exists to catch.
    const named = (key: string) => src.includes(`.${key}`) || src.includes(`"${key}"`);
    const referenced = leaves.filter((l) => {
      const parts = l.split(".");
      return parts.some((_, i) => named(parts.slice(0, parts.length - i).pop()!));
    });
    const ratio = referenced.length / leaves.length;
    expect(ratio, `only ${referenced.length}/${leaves.length} facts leaves are referenced by any assertion`)
      .toBeGreaterThan(0.85);
  });
});

describe("the section 28 and 42 artifacts exist", () => {
  const REQUIRED_28 = [
    "00-repository-map.md", "01-content-inventory.md", "02-content-audit.md",
    "target-information-architecture.md", "target-learning-model.md", "terminology-policy.md",
    "migration-map.md", "duplication-map.md", "gaps-and-contradictions.md", "decision-log.md",
    "validation-report.md", "analytics-plan.md", "accessibility-audit.md",
    "visual-asset-audit.md", "rollout-plan.md", "STATUS.md",
  ];
  const MACHINE_READABLE = [
    "content-inventory.json", "content-inventory.csv", "content-audit.json",
    "content-review-schedule.json", "question-bank.json", "interview-bank.json",
    "diagram-inventory.json", "code-example-inventory.json", "aws-architecture-inventory.json",
  ];

  it("every document section 28 names is present", () => {
    const missing = REQUIRED_28.filter((f) => !existsSync(`${DOCS}/${f}`));
    expect(missing, "section 28 names a document that does not exist").toEqual([]);
  });

  it("every machine-readable artifact is present", () => {
    const missing = MACHINE_READABLE.filter((f) => !existsSync(`${DOCS}/${f}`));
    expect(missing).toEqual([]);
  });

  it("no generated document is a stub", () => {
    for (const f of [...GENERATED, ...GENERATED_42]) {
      const body = readFileSync(`${DOCS}/${f}`, "utf8");
      expect(body.length, `${f} is too short to say anything`).toBeGreaterThan(1200);
    }
  });

  it("every document section 42 names is present, plus its three directories", () => {
    const missing = GENERATED_42.filter((f) => !existsSync(`${DOCS}/${f}`));
    expect(missing, "section 42 names a document that does not exist").toEqual([]);
    for (const d of ["concepts", "modules", "reviews"]) {
      expect(existsSync(`${DOCS}/${d}`), `${d}/ is missing`).toBe(true);
    }
  });
});

describe("the section 42 docs report what is NOT built", () => {
  // These docs describe systems that are mostly unimplemented, and the failure mode is a
  // document that restates the spec so the reader assumes it shipped. Each assertion
  // below pins a doc to an absence that facts.json measures — so if the feature is ever
  // built, the test fails and the doc has to be rewritten rather than silently becoming
  // wrong in the flattering direction.
  const read = (f: string) => readFileSync(`${DOCS}/${f}`, "utf8");
  const sys = facts.systems;

  it("saved-content-model.md says the feature does not exist", () => {
    expect(sys.savedContent.exists, "saved content now exists — rewrite the doc").toBe(false);
    expect(read("saved-content-model.md")).toContain("**Not built.**");
  });

  it("interview-mode.md says there is no interview route", () => {
    expect(sys.interviewMode.routeExists, "an interview surface now exists — rewrite the doc").toBe(false);
    const body = read("interview-mode.md");
    expect(body).toContain("the product surface does not");
  });

  it("the retention docs report the real number of queue sources", () => {
    const built = Object.values(sys.reviewQueue.sources).filter(Boolean).length;

    // The count is asserted against the SOURCE, not against the same object the generator
    // serialized. The previous version recomputed `filter(Boolean).length` over
    // `sources` — character-for-character the generator's own expression — so it proved
    // `Array.filter` is deterministic and left all ten predicates unchecked.
    //
    // What is checkable here: exactly one source is implemented, it is the interval
    // ladder, and `daily.ts` really does call `dueConcepts`. Everything else must be
    // absent from both scheduler modules, which is what makes 1-of-10 a measurement.
    const daily = readFileSync("src/lib/daily.ts", "utf8");
    const review = readFileSync("src/lib/review.ts", "utf8");
    expect(daily, "daily.ts no longer reads the interval ladder").toMatch(/dueConcepts/);
    expect(sys.reviewQueue.sources["concepts near forgetting"]).toBe(true);
    expect(built, "a queue source was implemented — update retention-engine.md").toBe(1);
    expect(sys.reviewQueue.sourcesImplemented).toBe(built);

    // And the signals that are reported ABSENT must really be absent, or the honest
    // number is a coincidence. Confidence is the load-bearing one: it is collected and
    // used elsewhere, so only the scheduler's silence makes "not read" true.
    expect(daily + review, "the scheduler now reads confidence — update the docs")
      .not.toMatch(/confidence/);
    expect(daily, "the scheduler now reads saved content — update the docs").not.toMatch(/saved/i);
    // The correction that matters: the first detectors reported 3 of 8 by matching
    // /prerequisite/ (a gate on what comes NEXT) and by probing dueConcepts twice.
    expect(read("retention-engine.md"), "the queue source count is stale")
      .toContain(`## The queue: ${built} of ${sys.reviewQueue.sourcesSpecified} sources`);
    expect(read("review-queue-model.md"))
      .toContain(`is ${built} of ${sys.reviewQueue.sourcesSpecified}`);
  });

  it("engagement-model.md admits confidence is not read by the scheduler", () => {
    // Captured, and used for the band cap and calibration gap — but not for scheduling,
    // which is where section 33 wants it. A doc that said "confidence-aware" would be
    // defensible-sounding and wrong.
    expect(sys.confidence.captured).toBe(true);
    expect(sys.confidence.usedForBandCap).toBe(true);
    expect(sys.confidence.usedByReviewQueue, "the scheduler now reads confidence — rewrite the doc").toBe(false);
    expect(read("engagement-model.md")).toMatch(/the review scheduler never reads it/);
  });

  it("the inventory-backed docs agree with the generated inventories", () => {
    const bank = JSON.parse(readFileSync(`${DOCS}/question-bank.json`, "utf8"));
    const ib = JSON.parse(readFileSync(`${DOCS}/interview-bank.json`, "utf8"));
    const ce = JSON.parse(readFileSync(`${DOCS}/code-example-inventory.json`, "utf8"));
    expect(read("question-bank-audit.md"), "the item count is stale").toContain(`${bank.items.length} items`);
    expect(read("evaluation-system.md"), "the scored count is stale")
      .toContain(`**${bank.items.filter((i: {scored: boolean}) => i.scored).length} are scored**`);
    expect(read("code-example-policy.md")).toContain(`${ce.examples.length} snippets`);
    const usable = ib.tracks.reduce((a: number, t: { usableItems: number }) => a + t.usableItems, 0);
    expect(read("interview-question-audit.md"), "the usable-item total is stale")
      .toContain(`Total usable: ${usable}`);
  });

  it("aws-architecture-standard.md reports the unpinned services rather than implying none", () => {
    const a = JSON.parse(readFileSync(`${DOCS}/aws-architecture-inventory.json`, "utf8"));
    const unpinned = [...new Set(a.claims.flatMap((x: { unpinnedServices: string[] }) => x.unpinnedServices))];
    const body = read("aws-architecture-standard.md");
    expect(body).toContain(`${a.claims.length} AWS claims`);
    expect(body, "the doc does not state how many services are unpinned")
      .toContain(`${unpinned.length} named services are **not** pinned`);
  });

  it("the work-package templates name the gaps in their own schemas", () => {
    // The architecture template must state which section 38.2 fields CodexArchitecture
    // cannot record, rather than quietly listing only the fields that exist.
    // Matched across a line wrap: the phrase breaks as "**absent from the\nschema**" in
    // the generated markdown, and a literal toContain failed on the newline while the
    // claim was already there. Asserting on formatting rather than meaning is how a
    // gate earns a reputation for crying wolf.
    expect(read("architecture-work-package-template.md").replace(/\s+/g, " "))
      .toContain("**absent from the schema**");
    expect(read("code-example-policy.md"), "the doc does not count its missing schema fields")
      .toMatch(/12 of its 16 fields are absent/);
  });
});

describe("the generated docs agree with facts.json", () => {
  // The load-bearing assertion of this file. Each doc interpolates counts from
  // facts.json, so a doc regenerated from stale facts, or edited by hand, diverges here.
  const read = (f: string) => readFileSync(`${DOCS}/${f}`, "utf8");

  it("the learning model reports the real per-stage coverage", () => {
    const body = read("target-learning-model.md");
    const cov = facts.learningModel.coverage;
    for (const [stage, n] of Object.entries(cov) as [string, number][]) {
      const label = stage === "worked" ? "Worked example" : stage[0].toUpperCase() + stage.slice(1);
      const row = body.match(new RegExp(`\\*\\*${label}\\*\\*.*?\\|\\s*(\\d+)\\s*\\|`));
      expect(row, `${label} has no row in the stage table`).toBeTruthy();
      expect(Number(row![1]), `the ${label} count is stale`).toBe(n);
    }
  });

  it("the validation report's counts match the measured suite", () => {
    const body = read("validation-report.md");
    expect(body).toContain(`${facts.validation.unitTests}\nunit tests`);
    expect(body).toContain(`${facts.validation.e2eTests} browser tests`);
    expect(body).toContain(`${facts.validation.contentValidators} content`);
    for (const name of facts.validation.baselineNames as string[]) {
      expect(body, `${name} is not documented in the validation report`).toContain(name);
    }
  });

  it("the STATUS dashboard reports the live learning-model coverage", () => {
    const body = read("STATUS.md");
    for (const [stage, n] of Object.entries(facts.learningModel.coverage) as [string, number][]) {
      const label = stage === "worked" ? "worked example" : stage;
      // Parsed structurally rather than by regex. Building the pattern as a string put
      // this three levels of escaping deep — TS source, template literal, RegExp — and
      // the pipes and `\d` arrived unescaped, matching nothing and reporting NaN. Same
      // class as the backspace in gen-facts.cjs: stop needing the escape.
      const row = body
        .split(NL)
        .map((l) => l.split("|").map((cell) => cell.trim()))
        .find((cells) => cells[1] === label);
      expect(row, `${label} has no row in the STATUS table`).toBeTruthy();
      expect(Number(row![2]), `STATUS reports a stale ${label} count`).toBe(n);
    }
    expect(body, "STATUS misstates the validator count")
      .toContain(`**${facts.validation.contentValidators} content validators**`);
    expect(body, "STATUS misstates the check count").toContain(`**${facts.content.checks} checks**`);
  });

  it("the analytics plan states zero instrumentation", () => {
    const body = read("analytics-plan.md");
    expect(body).toContain(`**${facts.analytics.trackingCalls} tracking calls.**`);
    expect(body).toContain(`${facts.analytics.progressFields} fields`);
  });

  it("the accessibility audit's counts match the source scan", () => {
    const body = read("accessibility-audit.md");
    expect(body).toContain(`${facts.a11y.tsxFiles} TSX files`);
    expect(body).toContain(`${facts.a11y.imagesWithAlt}/${facts.a11y.imagesTotal}\` images`);
  });

  it("the visual audit's figure counts match the content", () => {
    const body = read("visual-asset-audit.md");
    expect(body).toContain(`${facts.visual.figures} authored figures`);
    for (const [kind, n] of Object.entries(facts.visual.byKind) as [string, number][]) {
      const row = body.match(new RegExp(`\\\`${kind}\\\` \\| (\\d+) \\|`));
      expect(row, `figure kind ${kind} has no row`).toBeTruthy();
      expect(Number(row![1]), `the ${kind} count is stale`).toBe(n);
    }
  });

  it("the migration map and rollout plan agree about the route model", () => {
    const laddered = (facts.routing.routeIds as string[]).filter((x) => x.includes("-")).length;
    for (const f of ["migration-map.md", "rollout-plan.md"]) {
      expect(read(f), `${f} misstates the route count`).toContain(`${laddered} routes`);
    }
    expect(read("migration-map.md")).toContain(`${facts.routing.pageRoutes} page routes`);
  });

  it("no generated doc claims a Predict or Build coverage it does not have", () => {
    // The specific dishonesty worth blocking: a doc that reads as though the engines
    // being built means the content exists.
    const gapPredict = facts.learningModel.totalConcepts - facts.learningModel.coverage.predict;
    const gapBuild = facts.learningModel.totalConcepts - facts.learningModel.coverage.build;
    for (const f of ["migration-map.md", "rollout-plan.md"]) {
      const body = read(f);
      expect(body, `${f} does not state the Predict gap`).toContain(`${gapPredict} concepts`);
      expect(body, `${f} does not state the Build gap`).toContain(`${gapBuild}`);
    }
  });
});
