// Do the design documents still describe the platform that ships?
//
// The characteristic failure of a design doc is a number that was true when it was
// typed. Two of the counts in facts.json were wrong on their first run — `it(` missed
// all 87 Playwright tests, and a field named `emptyAxes` counted every axes figure — and
// both would have been quoted in a document as evidence.
//
// So the docs are generated from facts.json (tools/gen-docs.cjs) and this file closes
// the loop twice: facts.json must agree with the source it claims to measure, and the
// generated docs must agree with facts.json.
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, readdirSync } from "node:fs";
import { CHECKS } from "@/lib/checks";
import { CHECKPOINTS, CONCEPTS, ORDERED_DOMAINS } from "@/lib/curriculum";
import { LESSONS } from "@/lib/lessons";
import { BUILDS } from "@/lib/build";
import { ROUTES, STAGES } from "@/lib/routes";

const DOCS = "docs/transformation";
const facts = JSON.parse(readFileSync(`${DOCS}/facts.json`, "utf8"));
const CONCEPT_LESSONS = LESSONS.flatMap((l) => l.concepts);

// Regenerated by tools/gen-docs.cjs; each must agree with facts.json.
const GENERATED = [
  "target-learning-model.md",
  "validation-report.md",
  "analytics-plan.md",
  "accessibility-audit.md",
  "visual-asset-audit.md",
  "migration-map.md",
  "rollout-plan.md",
];

describe("facts.json agrees with the source it measures", () => {
  it("counts the content the app actually loads", () => {
    // Measured against the TypeScript modules, not by re-reading the JSON the generator
    // read. Re-parsing the same file would only prove JSON.parse is deterministic.
    expect(facts.content.spineConcepts).toBe(CONCEPTS.length);
    expect(facts.content.lessons).toBe(LESSONS.length);
    expect(facts.content.conceptLessons).toBe(CONCEPT_LESSONS.length);
    expect(facts.content.checkpoints).toBe(CHECKPOINTS.length);
    expect(facts.content.checkpointItems).toBe(CHECKPOINTS.reduce((a, c) => a + c.items.length, 0));
    expect(facts.content.checks).toBe(CHECKS.length);
    expect(facts.content.builds).toBe(BUILDS.length);
    expect(facts.content.domains).toBe(ORDERED_DOMAINS.length);
  });

  it("counts each check mechanic correctly", () => {
    const byKind: Record<string, number> = {};
    for (const k of CHECKS) byKind[k.kind] = (byKind[k.kind] ?? 0) + 1;
    expect(facts.content.checksByKind).toEqual(byKind);
  });

  it("measures the route model rather than restating it", () => {
    expect(facts.routing.stageCount).toBe(STAGES.length);
    for (const r of ROUTES) expect(facts.routing.routeIds).toContain(r.id);
  });

  it("the learning-stage coverage is derived from the content", () => {
    expect(facts.learningModel.coverage.predict)
      .toBe(CONCEPT_LESSONS.filter((c) => c.predict).length);
    expect(facts.learningModel.coverage.recall)
      .toBe(CONCEPT_LESSONS.filter((c) => c.flashcards?.length).length);
    expect(facts.learningModel.coverage.worked)
      .toBe(CONCEPT_LESSONS.filter((c) => c.example).length);
    expect(facts.learningModel.coverage.practice)
      .toBe(CONCEPT_LESSONS.filter((c) => CHECKS.some((k) => k.concept === c.slug)).length);
    expect(facts.learningModel.totalConcepts).toBe(CONCEPT_LESSONS.length);
  });

  it("reports Explain and Transfer as absent, because they are", () => {
    // If either is ever built, this test SHOULD fail — that is the signal to update the
    // learning model doc rather than leaving it claiming a gap that has been closed.
    expect(facts.learningModel.coverage.explain, "Explain now exists — update the docs").toBe(0);
    expect(facts.learningModel.coverage.transfer, "Transfer now exists — update the docs").toBe(0);
  });

  it("reports zero analytics, and would notice instrumentation appearing", () => {
    expect(facts.analytics.trackingCalls).toBe(0);
    expect(facts.analytics.fetchCallsToApi).toBe(0);
  });

  it("separates structural empty strings from missing translations", () => {
    // The naive count is 7 and every one is correct content: three cloze checks whose
    // sentence opens with a blank, and one deliberate `kind: "none"` figure opt-out.
    // Reporting "7 empty strings" would describe a translation gap that does not exist.
    expect(facts.i18n.emptyProse, "a real translation gap has appeared").toBe(0);
    expect(facts.i18n.emptyStructural).toBe(facts.i18n.structuralPaths.length);
    for (const p of facts.i18n.structuralPaths as string[]) {
      expect(p, `${p} is neither a cloze segment nor a none-diagram caption`)
        .toMatch(/(\.segments\.\d+\.|caption)/);
    }
  });

  it("has exactly as many Spanish strings as English ones", () => {
    expect(facts.i18n.es).toBe(facts.i18n.en);
  });

  it("counts Playwright tests, which use test() and not it()", () => {
    // The defect this replays: `it(` matched zero of the 87 Playwright tests, so the
    // validation report would have claimed no browser coverage existed.
    const specs = readdirSync("tests/visual").filter((f) => f.endsWith(".spec.ts"));
    expect(facts.validation.e2eSpecFiles).toBe(specs.length);
    const counted = specs.reduce(
      (a, f) => a + (readFileSync(`tests/visual/${f}`, "utf8").match(/^\s*(?:it|test)\(/gm) || []).length, 0);
    expect(facts.validation.e2eTests).toBe(counted);
    expect(facts.validation.e2eTests).toBeGreaterThan(0);
  });

  it("counts the validators the verify script actually runs", () => {
    const pkg = JSON.parse(readFileSync("package.json", "utf8"));
    const steps = (name: string) => pkg.scripts[name].split("&&").map((s: string) => s.trim()).filter(Boolean);
    expect(facts.validation.contentValidators).toBe(steps("content:check").length);
    expect(facts.validation.selfTests).toBe(steps("gates:selftest").length);
    expect(facts.validation.verifySteps).toBe(steps("verify").length);
  });
});

describe("the section 28 and 42 artifacts exist", () => {
  const REQUIRED_28 = [
    "00-repository-map.md", "01-content-inventory.md", "02-content-audit.md",
    "target-information-architecture.md", "target-learning-model.md", "terminology-policy.md",
    "migration-map.md", "duplication-map.md", "gaps-and-contradictions.md", "decision-log.md",
    "validation-report.md", "analytics-plan.md", "accessibility-audit.md",
    "visual-asset-audit.md", "rollout-plan.md", "STATUS.md",
  ];
  const MACHINE_READABLE = [
    "content-inventory.json", "content-inventory.csv", "content-audit.json",
    "content-review-schedule.json", "question-bank.json", "interview-bank.json",
    "diagram-inventory.json", "code-example-inventory.json", "aws-architecture-inventory.json",
  ];

  it("every document section 28 names is present", () => {
    const missing = REQUIRED_28.filter((f) => !existsSync(`${DOCS}/${f}`));
    expect(missing, "section 28 names a document that does not exist").toEqual([]);
  });

  it("every machine-readable artifact is present", () => {
    const missing = MACHINE_READABLE.filter((f) => !existsSync(`${DOCS}/${f}`));
    expect(missing).toEqual([]);
  });

  it("no generated document is a stub", () => {
    for (const f of GENERATED) {
      const body = readFileSync(`${DOCS}/${f}`, "utf8");
      expect(body.length, `${f} is too short to say anything`).toBeGreaterThan(1200);
      expect(body, `${f} does not state where its numbers come from`).toMatch(/facts\.json/);
    }
  });
});

describe("the generated docs agree with facts.json", () => {
  // The load-bearing assertion of this file. Each doc interpolates counts from
  // facts.json, so a doc regenerated from stale facts, or edited by hand, diverges here.
  const read = (f: string) => readFileSync(`${DOCS}/${f}`, "utf8");

  it("the learning model reports the real per-stage coverage", () => {
    const body = read("target-learning-model.md");
    const cov = facts.learningModel.coverage;
    for (const [stage, n] of Object.entries(cov) as [string, number][]) {
      const label = stage === "worked" ? "Worked example" : stage[0].toUpperCase() + stage.slice(1);
      const row = body.match(new RegExp(`\\*\\*${label}\\*\\*.*?\\|\\s*(\\d+)\\s*\\|`));
      expect(row, `${label} has no row in the stage table`).toBeTruthy();
      expect(Number(row![1]), `the ${label} count is stale`).toBe(n);
    }
  });

  it("the validation report's counts match the measured suite", () => {
    const body = read("validation-report.md");
    expect(body).toContain(`${facts.validation.unitTests}\nunit tests`);
    expect(body).toContain(`${facts.validation.e2eTests} browser tests`);
    expect(body).toContain(`${facts.validation.contentValidators} content`);
    for (const name of facts.validation.baselineNames as string[]) {
      expect(body, `${name} is not documented in the validation report`).toContain(name);
    }
  });

  it("the analytics plan states zero instrumentation", () => {
    const body = read("analytics-plan.md");
    expect(body).toContain(`**${facts.analytics.trackingCalls} tracking calls.**`);
    expect(body).toContain(`${facts.analytics.progressFields} fields`);
  });

  it("the accessibility audit's counts match the source scan", () => {
    const body = read("accessibility-audit.md");
    expect(body).toContain(`${facts.a11y.tsxFiles} TSX files`);
    expect(body).toContain(`${facts.a11y.imagesWithAlt}/${facts.a11y.imagesTotal}\` images`);
  });

  it("the visual audit's figure counts match the content", () => {
    const body = read("visual-asset-audit.md");
    expect(body).toContain(`${facts.visual.figures} authored figures`);
    for (const [kind, n] of Object.entries(facts.visual.byKind) as [string, number][]) {
      const row = body.match(new RegExp(`\\\`${kind}\\\` \\| (\\d+) \\|`));
      expect(row, `figure kind ${kind} has no row`).toBeTruthy();
      expect(Number(row![1]), `the ${kind} count is stale`).toBe(n);
    }
  });

  it("the migration map and rollout plan agree about the route model", () => {
    const laddered = (facts.routing.routeIds as string[]).filter((x) => x.includes("-")).length;
    for (const f of ["migration-map.md", "rollout-plan.md"]) {
      expect(read(f), `${f} misstates the route count`).toContain(`${laddered} routes`);
    }
    expect(read("migration-map.md")).toContain(`${facts.routing.pageRoutes} page routes`);
  });

  it("no generated doc claims a Predict or Build coverage it does not have", () => {
    // The specific dishonesty worth blocking: a doc that reads as though the engines
    // being built means the content exists.
    const gapPredict = facts.learningModel.totalConcepts - facts.learningModel.coverage.predict;
    const gapBuild = facts.learningModel.totalConcepts - facts.learningModel.coverage.build;
    for (const f of ["migration-map.md", "rollout-plan.md"]) {
      const body = read(f);
      expect(body, `${f} does not state the Predict gap`).toContain(`${gapPredict} concepts`);
      expect(body, `${f} does not state the Build gap`).toContain(`${gapBuild}`);
    }
  });
});
