import { chromium } from '@playwright/test';
const B='https://levelup.skillrealm.dev';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1440,height:1000}, reducedMotion:'reduce' });
const p = await ctx.newPage();
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push('PAGEERROR '+e.message));
await p.goto(B+'/en/today/', {waitUntil:'networkidle'}); await p.waitForTimeout(1200);
console.log('streak ribbon    :', await p.locator('.streak').count() > 0);
console.log('days-learned cap :', (await p.locator('.streak-cap').first().innerText().catch(()=>'')).trim());
console.log('brief card       :', await p.locator('.today-fresh, .today-card').count() > 0);
const begin = p.getByRole('button', {name:/Begin today/i});
if (await begin.count()) { await begin.click(); await p.waitForTimeout(900);
  console.log('concept pane     :', await p.locator('.lesson-content').count() > 0); }
await p.screenshot({path:'research/audit-2026-07-25/live-today.png', fullPage:false});
await p.goto(B+'/en/resources/', {waitUntil:'networkidle'}); await p.waitForTimeout(700);
console.log('resource groups  :', await p.locator('.resgroup').count());
await p.goto(B+'/en/learn/', {waitUntil:'networkidle'}); await p.waitForTimeout(700);
console.log('climb cells      :', await p.locator('.stage-cell').count());
const ov = await p.evaluate(()=>({sw:document.documentElement.scrollWidth, cw:document.documentElement.clientWidth}));
console.log('no overflow      :', ov.sw <= ov.cw+2);
console.log('ERRORS           :', errs.length? errs.slice(0,3).join(' | '):'none');
await b.close();
